version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      PORT: 9999
    ports:
      - 9999:9999
    volumes:
      - ..:/workspace
    command: sleep infinity
    
# Uncomment below lines to spawn mysql service
  # db:
  #   image: mysql:8.0
  #   restart: unless-stopped
  #   environment: 
  #     MYSQL_USER: "mysqluser"
  #     MYSQL_PASSWORD: "mysqlpassword"
  #     MYSQL_DATABASE: "mysqldb"
  #     MYSQL_ROOT_PASSWORD: "mysqlrootpassword"
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db_data:/var/lib/mysql

# Uncomment below to activate mysql volume
# volumes:
#   db_data: {}
